### PR TITLE
_colors.scss: Green should be #5b9e4d and not #589e4d

### PR DESCRIPTION
**Pull request by ghost**
We've been using the wrong shade of green this whole time! Absolutely unacceptable.

screen shot 2016-01-28 at 9 17 05 pm

Discovered during a chat with Chris:

screen shot 2016-01-28 at 9 18 52 pm

\+ @chrismorast @bsstoner

### CODE REVIEW

**Comment by tagawa** [comment]
Phew, lucky escape!

**Comment by bsstoner** [comment]
3uqmjonevctx

**Comment by bsstoner** [comment]
:+1:

**Comment by andrey-p** [comment]
:green_heart:

**Pull request merged**
